[build]
  publish = "_site"
  command = "DEBUG=* eleventy"

[[redirects]]
from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
  cache-control = '''
  stale-if-error=90, 
  stale-while-revalidate=30, 
  max-age=30'''